// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
// import { AnimationProvider } from "@/app/context/AnimationContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <AnimationProvider>{children}</AnimationProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";
import { AnimationProvider } from "@/app/context/AnimationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const crustaceans = localFont({
//   src: "@/public/fonts/Crustaceans/Crustaceans-Signature-Regular.otf",
//   variable: "--font-crustaceans",
//   display: "swap",
// });

const crustaceans = localFont({
  src: [
    {
      path: "../../public/fonts/Crustaceans/Crustaceans-Signature-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-crustaceans",
  display: "swap",
});

const ivypresto = localFont({
  src: [
    {
      path: "../../public/fonts/IvyPresto/Ivy-Presto.otf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-ivypresto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${crustaceans.variable} ${ivypresto.variable} antialiased`}
      >
        <AnimationProvider>{children}</AnimationProvider>
      </body>
    </html>
  );
}
